# author lp 9/12/24
x = 21
y = 21
z = 21
w = 21
t = 21
a = 21
i = 21
x += 5
print("x after x += 5:", x)
x = 21  
x = x + 5
print("x after x = x + 5:", x)
y = y - 3
print("y after y = y - 3:", y)
y = 21  
y -= 3
print("y after y -= 3:", y)
z **= 2
print("z after z **= 2:", z)
z = 21  
z = z ** 2
print("z after z = z ** 2:", z)
w = w % 2
print("w after w = w % 2:", w)
w = 21  # Resetting w
w %= 2
print("w after w %= 2:", w)
t = t / 5
print("t after t = t / 5:", t)
t = 21  # Resetting t
t /= 5
print("t after t /= 5:", t)
a *= 12
print("a after a *= 12:", a)
a = 21  # Resetting a
a = a * 12
print("a after a = a * 12:", a)
i = i // 7
print("i after i = i // 7:", i)
i = 21  # Resetting i
i //= 7
print("i after i //= 7:", i)